name: tinkoff_helper
description: App for working with Tinkoff API
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  vertical_tabs_flutter: ^1.0.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  l: ^3.2.0
  bloc_concurrency: ^0.2.1
  grpc: ^3.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  protobuf: ^2.1.0
  sliver_table: ^0.0.2
  url_launcher: ^6.1.10
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  lint: ^2.0.1

flutter:
  uses-material-design: true
