name: tinkoff_helper
description: App for working with Tinkoff API
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.2.1
  collection: ^1.17.2
  fixnum: ^1.1.0
  flutter_bloc: ^8.1.2
  freezed: ^2.4.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  grpc: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.1
  l: ^4.0.2
  path_provider: ^2.1.1
  protobuf: 3.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: 3.0.0
  build_runner: ^2.3.3
  lint: ^2.0.1

flutter:
  uses-material-design: true
